name: Bulletbox Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Verify files
        run: |
          ls
          ls lib

      - name: Run JReleaser
        uses: jreleaser/jreleaser-action@v2
        with:
          arguments: full-release
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}